### ISSUE TITLE
Error: Failed building wheel for tokenizers

### ISSUE THREAD

**Issue by abitofalchemy** [ptarau/pytalk#1]
"ERROR: Could not build wheels for tokenizers which use PEP 517 and cannot be installed directly"

What dependencies might this be related to? 
Do you think this related to a hardware incompatibility?

**Comment by ptarau** [comment]
Tested build on OS X Catalina and Ubuntu 18.x LTS both with python3.6 or higher, 3.7.x on the Mac. Failing to build on my Windows VM, as torch does not build there.  What OS / Machine you tried the build? Updated also the readme and checked dependencies. Latest version now at pypi as doctalk 0.3.0.
